on:
  schedule: # Execute a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Geração de Snake Animation
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: GeorgeAlbuquerq
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Atualiza branch com a snake animation
      - name: Commit e enviar Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: github-snake
          path: dist/

      - name: Deploy Snake Animation
        uses: actions/checkout@v2
        with:
          ref: output

      - run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add dist/*
          git commit -m "Atualizando Snake Animation"
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
